### PR TITLE
merge with upstream

### PR DESCRIPTION
**Pull request by 8tomat8**
Merged all the changes from the `upstream/master` and moved setting to globals, so we can offer it as a soution to author.

### CODE REVIEW

**Comment by ubombi** [comment]
There is only [old rebased commit ](https://github.com/hatch-studio/chromedp/pull/1/commits/f0c9f13059571fb05992364e49b8bc2e3720b8ce)

I don't see 

> and moved setting to globals

**Comment by 8tomat8** [comment]
> There is only [old rebased commit ](https://github.com/hatch-studio/chromedp/pull/1/commits/f0c9f13059571fb05992364e49b8bc2e3720b8ce)
> 
> I don't see
> 
> > and moved setting to globals

This is exactly it. what else do you expect to see?

**Comment by 8tomat8** [comment]
https://linear.app/hatchstudio/issue/BEC-130/merge-chromedp-change-back

**Comment by ubombi** [comment]
I misunderstood. I thought that you  wan't to make it configurable

**Review by ubombi — APPROVED** [review]
ok

**Comment by 8tomat8** [comment]
> I misunderstood. I thought that you want to make it configurable.

It is. As a global var. I didn't find a good way to pass it from the client, so better to create a PR in the upstream and hear the opinion of author

**Comment by 8tomat8** [comment]
I can do better

**Pull request closed without merging**
